[build]
compiler = "clang++"
target = "main"

[paths]
src = "src"
include = "include"
build = "build"

[compiler]
flags = ["-Wall", "-std=c++20", "-O3"]
definitions = { VERSION = "0.1.0" }
warnings_as_errors = true
