
[build]
compiler = "g++"
target = "hello"

[cross]
target = "aarch64-unknown-darwin"
toolchain = ""
sysroot = ""
extra_flags = []

[profiles.debug]
opt_level = "0"
debug_info = true
lto = false

[profiles.release]
opt_level = "3"
debug_info = false
lto = true
extra_flags = ["-march=native"]

[paths]
src = "src"
include = ["include"]
build = "build"

[compiler]
flags = ["-Wall", "-std=c++20"]
definitions = { VERSION = "0.1.0" }
warnings_as_errors = true
library_paths = []
libraries = []
